// Print the cell width the VENDORED xterm.js gives every code point, as ranges.
//
//   node gen_widths.js json          the ranges as JSON on stdout, for the parity test
//   node gen_widths.js go <file>     write screen_width.go's tables to <file>
//
// The board loads no unicode addon, so xterm runs its default UnicodeV6 provider,
// and that is the table screen.go has to agree with. Run this again, and commit
// the result, whenever internal/api/web/vendor/xterm.js changes.
const fs = require("fs");
const path = require("path");
const { Terminal } = require(path.join(__dirname, "..", "..", "api", "web", "vendor", "xterm.js"));

const t = new Terminal({ cols: 80, rows: 24, allowProposedApi: true });
const svc = t._core.unicodeService;

function ranges(want) {
  const out = [];
  let start = -1;
  for (let cp = 0; cp <= 0x110000; cp++) {
    const hit = cp < 0x110000 && !(cp >= 0xd800 && cp <= 0xdfff) && svc.wcwidth(cp) === want;
    if (hit && start < 0) start = cp;
    if (!hit && start >= 0) {
      out.push([start, cp - 1]);
      start = -1;
    }
  }
  return out;
}

// Above 0x7e is the only place the two differ from ASCII, so start the tables
// there: C0 and DEL are step's business, not a width's.
const clip = (rs) => rs.filter(([, b]) => b >= 0x7f).map(([a, b]) => [Math.max(a, 0x7f), b]);
const wide = clip(ranges(2));
const zero = clip(ranges(0));

if (process.argv[2] === "json") {
  process.stdout.write(JSON.stringify({ wide, zero }));
} else if (process.argv[2] === "go") {
  const fmt = (rs) => rs.map(([a, b]) => `\t{0x${a.toString(16)}, 0x${b.toString(16)}},`).join("\n");
  fs.writeFileSync(
    process.argv[3],
    `package daemon

// Code generated by testdata/gen_widths.js from the vendored xterm.js. DO NOT EDIT.
// TestWidthMatchesXterm fails when these drift from it.

var wideRanges = [][2]rune{
${fmt(wide)}
}

var zeroRanges = [][2]rune{
${fmt(zero)}
}
`,
  );
} else {
  console.error("usage: gen_widths.js json | go <file>");
  process.exit(2);
}
