package api

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// Bringing a Windows Terminal scheme in.
//
// The conversion has exactly one trap in it and it is silent: Windows Terminal
// calls magenta `purple`, so a scheme converted by hand puts a colour that IS
// magenta into a slot xterm never reads, and every magenta in every session
// comes out as the terminal's default. Nothing about that looks wrong on a
// screenshot, which is why it is the first test in this file.

func themeReq(t *testing.T, srv *Server, method, path, body string) *httptest.ResponseRecorder {
	t.Helper()
	req := httptest.NewRequest(method, path, strings.NewReader(body))
	rec := httptest.NewRecorder()
	srv.Handler().ServeHTTP(rec, req)
	return rec
}

// brought reads the themes back the way the board does.
func brought(t *testing.T, srv *Server) map[string]map[string]string {
	t.Helper()
	rec := themeReq(t, srv, http.MethodGet, "/v1/themes", "")
	if rec.Code != http.StatusOK {
		t.Fatalf("listing themes answered %d: %s", rec.Code, rec.Body.String())
	}
	var out struct {
		Themes []struct {
			Name    string            `json:"name"`
			Palette map[string]string `json:"palette"`
		} `json:"themes"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &out); err != nil {
		t.Fatal(err)
	}
	got := map[string]map[string]string{}
	for _, th := range out.Themes {
		got[th.Name] = th.Palette
	}
	return got
}

// campbell is one real Windows Terminal scheme, colours and all.
const campbell = `{
  "name": "Campbell",
  "background": "#0C0C0C", "foreground": "#CCCCCC",
  "cursorColor": "#FFFFFF", "selectionBackground": "#FFFFFF",
  "black": "#0C0C0C", "red": "#C50F1F", "green": "#13A10E", "yellow": "#C19C00",
  "blue": "#0037DA", "purple": "#881798", "cyan": "#3A96DD", "white": "#CCCCCC",
  "brightBlack": "#767676", "brightRed": "#E74856", "brightGreen": "#16C60C",
  "brightYellow": "#F9F1A5", "brightBlue": "#3B78FF", "brightPurple": "#B4009E",
  "brightCyan": "#61D6D6", "brightWhite": "#F2F2F2"
}`

func TestWindowsTerminalPurpleLandsInMagenta(t *testing.T) {
	srv, _, _ := fileServer(t)

	rec := themeReq(t, srv, http.MethodPost, "/v1/themes/import", campbell)
	if rec.Code != http.StatusOK {
		t.Fatalf("importing campbell answered %d: %s", rec.Code, rec.Body.String())
	}
	p := brought(t, srv)["campbell"]
	if p == nil {
		t.Fatal("campbell is not there after importing it")
	}
	if p["magenta"] != "#881798" {
		t.Errorf("magenta is %q, wanted windows terminal's purple #881798", p["magenta"])
	}
	if p["brightMagenta"] != "#b4009e" {
		t.Errorf("brightMagenta is %q, wanted #b4009e", p["brightMagenta"])
	}
	// The other rename, and the one nobody would miss because a terminal with
	// no cursor colour still has a cursor.
	if p["cursor"] != "#ffffff" {
		t.Errorf("cursor is %q, wanted cursorColor #ffffff", p["cursor"])
	}
	// Windows Terminal has no such field, and inventing one would be atrium
	// deciding what somebody's theme looks like.
	if p["selectionForeground"] != "" {
		t.Errorf("selectionForeground was invented as %q", p["selectionForeground"])
	}
}

// A REAL settings.json HAS COMMENTS IN IT, because Windows Terminal writes them.
// Refusing the file the format's own editor produces would leave the import
// working only on a file somebody had cleaned up by hand first.
func TestAWholeSettingsFileWithCommentsIsRead(t *testing.T) {
	srv, _, _ := fileServer(t)

	body := `{
  // This file was initially generated by Windows Terminal.
  "$help": "https://aka.ms/terminal-documentation",
  "profiles": {
    "list": [
      // The comment marker below is INSIDE a string and is not a comment.
      { "name": "Ubuntu", "commandline": "wsl.exe -d Ubuntu // as me" }
    ]
  },
  /* the schemes, which is the half atrium wants */
  "schemes": [
    ` + campbell + `,
    // one that was commented out, leaving a comma behind it
  ]
}`
	rec := themeReq(t, srv, http.MethodPost, "/v1/themes/import", body)
	if rec.Code != http.StatusOK {
		t.Fatalf("a settings.json with comments answered %d: %s", rec.Code, rec.Body.String())
	}
	if brought(t, srv)["campbell"] == nil {
		t.Fatal("the scheme in a commented settings.json did not come through")
	}
}

// The array on its own, which is what somebody pastes when they know where the
// schemes are.
func TestJustTheSchemesArrayIsRead(t *testing.T) {
	srv, _, _ := fileServer(t)

	rec := themeReq(t, srv, http.MethodPost, "/v1/themes/import", "["+campbell+"]")
	if rec.Code != http.StatusOK {
		t.Fatalf("a bare array answered %d: %s", rec.Code, rec.Body.String())
	}
	if brought(t, srv)["campbell"] == nil {
		t.Fatal("a scheme in a bare array did not come through")
	}
}

func TestASchemeNameBecomesAThemeName(t *testing.T) {
	for _, c := range []struct{ in, want string }{
		{"Campbell", "campbell"},
		{"One Half Dark", "one-half-dark"},
		{"Solarized Dark (higher contrast)", "solarized-dark-higher-contrast"},
		{"  Tango  Light ", "tango-light"},
		{"C64", "c64"},
		{"...", ""},
	} {
		if got := SlugTheme(c.in); got != c.want {
			t.Errorf("%q became %q, wanted %q", c.in, got, c.want)
		}
	}
}

// ONE BAD SCHEME DOES NOT LOSE THE OTHER FIFTY. A settings.json is somebody's
// whole collection, and a colour atrium will not take in one of them is not a
// reason to import none of them.
func TestOneUnusableSchemeDoesNotStopTheRest(t *testing.T) {
	srv, _, _ := fileServer(t)

	broken := strings.Replace(campbell, `"name": "Campbell"`, `"name": "Broken"`, 1)
	broken = strings.Replace(broken, `"green": "#13A10E"`, `"green": "chartreuse"`, 1)
	rec := themeReq(t, srv, http.MethodPost, "/v1/themes/import",
		"["+campbell+","+broken+"]")
	if rec.Code != http.StatusOK {
		t.Fatalf("answered %d: %s", rec.Code, rec.Body.String())
	}
	if brought(t, srv)["campbell"] == nil {
		t.Fatal("the good scheme was lost because the one beside it was bad")
	}
	if brought(t, srv)["broken"] != nil {
		t.Fatal("a scheme with a word where a colour goes was stored")
	}
	// And the one that was skipped is named, because a count sends somebody
	// back to the file to guess which.
	if !strings.Contains(rec.Body.String(), "broken") {
		t.Errorf("the skipped scheme is not named in the answer: %s", rec.Body.String())
	}
}

// The dangerous direction never overwrites silently, which is the same rule the
// configuration import follows.
func TestImportingTwiceKeepsWhatIsThereUnlessTold(t *testing.T) {
	srv, _, _ := fileServer(t)

	themeReq(t, srv, http.MethodPost, "/v1/themes/import", campbell)
	// Edited by hand afterwards, which is the state worth protecting.
	mine := `{"background":"#0c0c0c","foreground":"#cccccc","black":"#0c0c0c","red":"#ff0000",
		"green":"#13a10e","yellow":"#c19c00","blue":"#0037da","magenta":"#881798",
		"cyan":"#3a96dd","white":"#cccccc","brightBlack":"#767676","brightRed":"#e74856",
		"brightGreen":"#16c60c","brightYellow":"#f9f1a5","brightBlue":"#3b78ff",
		"brightMagenta":"#b4009e","brightCyan":"#61d6d6","brightWhite":"#f2f2f2"}`
	if rec := themeReq(t, srv, http.MethodPut, "/v1/themes/campbell", mine); rec.Code != http.StatusOK {
		t.Fatalf("editing answered %d: %s", rec.Code, rec.Body.String())
	}

	rec := themeReq(t, srv, http.MethodPost, "/v1/themes/import", campbell)
	if rec.Code != http.StatusOK {
		t.Fatalf("answered %d: %s", rec.Code, rec.Body.String())
	}
	if got := brought(t, srv)["campbell"]["red"]; got != "#ff0000" {
		t.Errorf("importing again overwrote an edited theme: red is %q", got)
	}

	rec = themeReq(t, srv, http.MethodPost, "/v1/themes/import?force=1", campbell)
	if rec.Code != http.StatusOK {
		t.Fatalf("answered %d: %s", rec.Code, rec.Body.String())
	}
	if got := brought(t, srv)["campbell"]["red"]; got != "#c50f1f" {
		t.Errorf("overwrite was asked for and did not happen: red is %q", got)
	}
}

// The editor's refusals arrive as something the operator can act on, which
// means a 400 naming the box rather than a 500.
func TestEditingRefusesAColourThatIsNotOneAndSaysWhich(t *testing.T) {
	srv, _, _ := fileServer(t)

	rec := themeReq(t, srv, http.MethodPut, "/v1/themes/mine",
		`{"background":"#000000","foreground":"#cccccc","black":"red"}`)
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("answered %d, wanted 400: %s", rec.Code, rec.Body.String())
	}
	if !strings.Contains(rec.Body.String(), "black") {
		t.Errorf("the refusal does not name the colour that was wrong: %s", rec.Body.String())
	}
}

func TestDeletingAThemeTakesItOffTheList(t *testing.T) {
	srv, _, _ := fileServer(t)

	themeReq(t, srv, http.MethodPost, "/v1/themes/import", campbell)
	if rec := themeReq(t, srv, http.MethodDelete, "/v1/themes/campbell", ""); rec.Code != http.StatusOK {
		t.Fatalf("deleting answered %d: %s", rec.Code, rec.Body.String())
	}
	if brought(t, srv)["campbell"] != nil {
		t.Fatal("the theme is still listed after being deleted")
	}
}

// The editor draws its boxes from this list rather than from a second list in
// the page, which is the same rule the skin picker follows.
func TestTheSlotsGoOutWithTheThemes(t *testing.T) {
	srv, _, _ := fileServer(t)

	rec := themeReq(t, srv, http.MethodGet, "/v1/themes", "")
	var out struct {
		Slots []struct {
			Name     string `json:"name"`
			Required bool   `json:"required"`
		} `json:"slots"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &out); err != nil {
		t.Fatal(err)
	}
	if len(out.Slots) != 21 {
		t.Fatalf("%d slots, wanted twenty one: five and the sixteen ansi colours", len(out.Slots))
	}
	want := map[string]bool{"magenta": true, "brightMagenta": true, "selectionForeground": false}
	for name, required := range want {
		found := false
		for _, s := range out.Slots {
			if s.Name != name {
				continue
			}
			found = true
			if s.Required != required {
				t.Errorf("%s is required=%v, wanted %v", name, s.Required, required)
			}
		}
		if !found {
			t.Errorf("%s is not in the slots the editor is told to draw", name)
		}
	}
}

func TestSomethingThatIsNotASchemeIsRefusedWithSomewhereToGo(t *testing.T) {
	srv, _, _ := fileServer(t)

	rec := themeReq(t, srv, http.MethodPost, "/v1/themes/import", "not json at all")
	if rec.Code != http.StatusBadRequest {
		t.Fatalf("answered %d, wanted 400", rec.Code)
	}
	if !strings.Contains(rec.Body.String(), "settings.json") {
		t.Errorf("the refusal does not say what to paste: %s", rec.Body.String())
	}
}
